.TH "GPXSee" "1" "" "" ""
.SH "NAME"
GPXSee \- a GPS log file viewer and analyzer

.SH SYNOPSIS
.B gpxsee
.RI [ FILES ]

.SH "DESCRIPTION"
.PP
GPXSee is a Qt based tool for visualizing and analyzing GPX, TCX, FIT, KML, IGC, NMEA and Garmin CSV files.
.PP
Its main features are:
 * User-definable online maps (OSM/Google tiles, WMTS, WMS)
 * Offline maps (OziExplorer maps, TrekBuddy maps/atlases, GeoTIFF images)
 * Elevation, speed, heart rate, cadence, power and temperature graphs
 * Support for multiple tracks in one view
 * Support for POI files
 * Print/export to PDF
 * Full\-screen mode
 * Opens GPX, TCX, FIT, KML, IGC, NMEA and Garmin CSV files

.SH "SEE ALSO"
You can find more about the program on its homepage: http://gpxsee.org
.SH "AUTHOR"
GPSSee was written by:
  Martin Tůma <tumic@cbox.cz>

